 export const LEAD_ACTIONS = {
  // Loading
  SET_LOADING: "SET_LOADING",

  // Error
  SET_ERROR: "SET_ERROR",
  CLEAR_ERROR: "CLEAR_ERROR",

  // Leads
  GET_LEADS: "GET_LEADS",
  ADD_LEAD: "ADD_LEAD",
  UPDATE_LEAD: "UPDATE_LEAD",
  DELETE_LEAD: "DELETE_LEAD",

  // Selected Lead
  SET_SELECTED_LEAD: "SET_SELECTED_LEAD",

  // Filters
  SET_FILTERS: "SET_FILTERS",
  RESET_FILTERS: "RESET_FILTERS",


  SET_AGENTS: "SET_AGENTS",
ADD_AGENT: "ADD_AGENT",
};